const pianoKeyboard = [
    /*{ color: 'white', note: 'C2' }, 
    { color: 'black', note: 'C#2'}, 
    { color: 'white', note: 'D2' },  
    { color: 'black', note: 'D#2'},  
    { color: 'white', note: 'E2' },
    { color: 'white', note: 'F2' },
    { color: 'black', note: 'F#2'},
    { color: 'white', note: 'G2' },
    { color: 'black', note: 'G#2'},
    { color: 'white', note: 'A2' },
    { color: 'black', note: 'A#2'},
    { color: 'white', note: 'B2' },*/
                
    { color: 'white', note: 'C3' }, 
    { color: 'black', note: 'C#3'}, 
    { color: 'white', note: 'D3' },  
    { color: 'black', note: 'D#3'},  
    { color: 'white', note: 'E3' },
    { color: 'white', note: 'F3' },
    { color: 'black', note: 'F#3'},
    { color: 'white', note: 'G3' },
    { color: 'black', note: 'G#3'},
    { color: 'white', note: 'A3' },
    { color: 'black', note: 'A#3'},
    { color: 'white', note: 'B3' }, 

    { color: 'white', note: 'C4' },
    { color: 'black', note: 'C#4'},
    { color: 'white', note: 'D4' },
    { color: 'black', note: 'D#4'},
    { color: 'white', note: 'E4' },
    { color: 'white', note: 'F4' },
    { color: 'black', note: 'F#4'},
    { color: 'white', note: 'G4' },
    { color: 'black', note: 'G#4'},
    { color: 'white', note: 'A4' },
    { color: 'black', note: 'A#4'},
    { color: 'white', note: 'B4' },

    { color: 'white', note: 'C5' },
    { color: 'black', note: 'C#5'},
    { color: 'white', note: 'D5' },
    { color: 'black', note: 'D#5'},
    { color: 'white', note: 'E5' },
    { color: 'white', note: 'F5' },
    { color: 'black', note: 'F#5'},
    { color: 'white', note: 'G5' },
    { color: 'black', note: 'G#5'},
    { color: 'white', note: 'A5' },
    { color: 'black', note: 'A#5'},
    { color: 'white', note: 'B5' },

    { color: 'white', note: 'C6' },/*
    { color: 'black', note: 'C#6'}, 
    { color: 'white', note: 'D6' },  
    { color: 'black', note: 'D#6'},  
    { color: 'white', note: 'E6' },
    { color: 'white', note: 'F6' },
    { color: 'black', note: 'F#6'},
    { color: 'white', note: 'G6' },
    { color: 'black', note: 'G#6'},
    { color: 'white', note: 'A6' },
    { color: 'black', note: 'A#6'},
    { color: 'white', note: 'B6' }, 
                
    { color: 'white', note: 'C7' } }*/
];

export default pianoKeyboard;